//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceComApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopSale
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int ProductID { get; set; }
        public double Amount { get; set; }
        public int ShopID { get; set; }
        public int UserID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual User User { get; set; }
    }
}
